- name: Setup NuGet
  uses: NuGet/setup-nuget@v2

- name: Restore and verify NuGet packages
  shell: powershell
  run:
    |
    powershell -ExecutionPolicy Bypass -File scripts/restore-and-verify.ps1

- name: Upload NuGet offline packages
  uses: actions/upload-artifact@v4
  with:
    name: nuget-offline-packages
    path: nupkgs
