name: NuGet Offline Mirror

on:
  workflow_dispatch:
  push:
    paths:
      - packages.txt

jobs:
  mirror:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NuGet CLI
        run: choco install nuget.commandline -y

      - name: Restore and verify NuGet packages
        run:
          |
          powershell -ExecutionPolicy Bypass -File scripts/restore-and-verify.ps1

      - name: Zip NuGet packages
        run:
          |
          powershell Compress-Archive -Path output/nupkgs -DestinationPath nuget-offline-packages.zip

      - name: Upload NuGet packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-offline-packages
          path: nuget-offline-packages.zip
          retention-days: 30
